language: dart
dist: osx
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/Flutter-Streamliner/flutter_messenger.git
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter --version
script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pub test/
cache:
  directories:
    - $HOME/.pub-cache